name: Bug Report
description: Report a problem with JDK 26 EA installation or functionality
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us resolve the issue.

  - type: dropdown
    id: installation-type
    attributes:
      label: Installation Type
      description: How did you install JDK 26 EA?
      options:
        - Cask (brew install --cask jdk26ea)
        - Formula (brew install jdk26ea)
        - Other
    validations:
      required: true

  - type: input
    id: jdk-build
    attributes:
      label: JDK 26 EA Build Number
      description: Which build number are you using?
      placeholder: "e.g., 26-ea+20"
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: Please provide your system details
      placeholder: |
        macOS version: (run `sw_vers`)
        Architecture: (ARM64/Intel)
        Homebrew version: (run `brew --version`)
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. See error '...'
        3. Expected '...' but got '...'
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Please paste any error messages or relevant output
      placeholder: Paste error output here
      render: shell

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected outcome

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: Any other relevant information
