name: Validate

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate-syntax:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@c39f0335940fb3214046dce5a5d2f94ed275ab4b

      - name: Validate cask syntax
        run: |
          brew style Casks/jdk26ea.rb
          ruby -c Casks/jdk26ea.rb

      - name: Audit cask
        run: |
          brew audit --cask artagon/jdk26ea/jdk26ea

      - name: Validate formula syntax
        run: |
          brew style Formula/jdk26ea.rb
          ruby -c Formula/jdk26ea.rb

  test-install-macos:
    strategy:
      matrix:
        os: [macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@c39f0335940fb3214046dce5a5d2f94ed275ab4b

      - name: Test cask installation
        run: |
          brew install --cask artagon/jdk26ea/jdk26ea

      - name: Verify installation
        run: |
          if [ -d "/Library/Java/JavaVirtualMachines/jdk-26-ea.jdk" ]; then
            echo "✅ JDK installed successfully"
            /Library/Java/JavaVirtualMachines/jdk-26-ea.jdk/Contents/Home/bin/java -version
          else
            echo "❌ JDK installation failed"
            exit 1
          fi

      - name: Cleanup
        if: always()
        run: |
          brew uninstall --cask artagon/jdk26ea/jdk26ea || true

  test-install-linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x64
          - os: ubuntu-24.04
            arch: x64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@c39f0335940fb3214046dce5a5d2f94ed275ab4b

      - name: Display system info
        run: |
          echo "OS: $(uname -s)"
          echo "Arch: $(uname -m)"
          echo "Distribution: $(cat /etc/os-release | grep PRETTY_NAME)"

      - name: Test formula installation
        run: |
          brew install artagon/jdk26ea/jdk26ea

      - name: Verify installation
        run: |
          JDK_PREFIX="$(brew --prefix jdk26ea)"
          if [ -d "$JDK_PREFIX" ]; then
            echo "✅ JDK installed successfully at $JDK_PREFIX"
            "$JDK_PREFIX/bin/java" -version
          else
            echo "❌ JDK installation failed"
            exit 1
          fi

      - name: Test JAVA_HOME setup
        run: |
          export JAVA_HOME="$(brew --prefix jdk26ea)"
          echo "JAVA_HOME=$JAVA_HOME"
          echo "Testing java compiler and runtime..."
          "$JAVA_HOME/bin/java" -version
          "$JAVA_HOME/bin/javac" -version

      - name: Test basic Java functionality
        run: |
          export JAVA_HOME="$(brew --prefix jdk26ea)"
          export PATH="$JAVA_HOME/bin:$PATH"

          # Create and compile a test program
          cat > HelloWorld.java << 'EOF'
          public class HelloWorld {
              public static void main(String[] args) {
                  System.out.println("JDK 26 EA is working!");
                  System.out.println("Java version: " + System.getProperty("java.version"));
              }
          }
          EOF

          javac HelloWorld.java
          java HelloWorld

      - name: Cleanup
        if: always()
        run: |
          brew uninstall --formula jdk26ea || true

  validation-status:
    name: Validation Status
    runs-on: ubuntu-latest
    needs:
      - validate-syntax
      - test-install-macos
      - test-install-linux
    steps:
      - name: Confirm completion
        run: echo "✅ All validation jobs completed successfully."

      - name: Publish Validate status for branch protection
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          gh api \
            --method POST \
            "repos/${REPO}/statuses/${SHA}" \
            -f state=success \
            -f context=Validate \
            -f description="All validation jobs completed successfully."
